# 2025-01-15: ubuntu:latest = 24.04, ubuntu:rolling = 24.10, ubuntu:devel = 25.04
# See https://hub.docker.com/_/ubuntu
image: ubuntu:rolling

include:
  - component: "gitlab.gnome.org/GNOME/citemplates/release-service@master"
    inputs:
      job-stage: "release"
      dist-job-name: "build_release_tarball"
      tarball-artifact-path: "_build/meson-dist/${CI_PROJECT_NAME}-${CI_COMMIT_TAG}.tar.xz"

stages:
  - build
  - deploy
  - release

variables:
  MESON_GCC_DEPS: g++
                  gettext
                  git
                  yelp-tools
                  gtk-doc-tools
                  python3-pygments
                  python3-setuptools
                  libglib2.0-dev
                  libatk1.0-dev
                  mm-common
                  libsigc++-3.0-dev
                  libglibmm-2.68-dev
                  libxml-libxml-perl
                  meson
                  ninja-build
                  glib-networking
  GIO_EXTRA_MODULES: "/usr/lib/x86_64-linux-gnu/gio/modules"
  GIT_SUBMODULE_STRATEGY: normal

.build_default:
  before_script:
    - export DEBIAN_FRONTEND=noninteractive
    - apt update && apt -y upgrade && apt -y install $DEPENDENCIES

release_gcc_build:
  extends: .build_default
  stage: build
  variables:
    DEPENDENCIES: $MESON_GCC_DEPS apt-file libglibmm-2.68-doc
  script:
    - apt-file update
    - apt-file list libglibmm-2.68-doc
    - pkg-config --variable=doxytagfile glibmm-2.68
    - ls -l /usr/share/doc/glibmm-2.68
    - ls -l /usr/share/doc/glibmm-2.68/reference
    - ls -l /usr/share/doc/libglibmm-2.68-doc
    - ls -l /usr/share/doc/libglibmm-2.68-doc/reference
    - mkdir _build && cd _build
    # -Ddebug=false + -Doptimization=3 correspond to -Dbuildtype=release
    - meson setup --prefix=/usr --libdir=lib -Ddebug=false -Doptimization=3 -Dwarnings=fatal -Dwarning_level=3 -Dwerror=true
    - meson compile
    - meson test
    - meson install --quiet
  artifacts:
    when: always
    paths:
      - _build/doc/reference

# Publish reference documentation at gnome.pages.gitlab.gnome.org/atkmm
pages:
  stage: deploy
  needs: [release_gcc_build]
  script:
    - mkdir public
    - mv _build/doc/reference/html/* public
  artifacts:
    paths:
      - public
  rules:
    - if: $CI_COMMIT_BRANCH == $CI_DEFAULT_BRANCH

build_release_tarball:
  extends: .build_default
  stage: build
  needs: []
  rules:
    - if: $CI_COMMIT_TAG  # Run this job when a tag is created
    - when: manual        # and when manually triggered.
      allow_failure: true # Don't block the CI pipeline until triggered.
  variables:
    DEPENDENCIES: $MESON_GCC_DEPS
  script:
    - mkdir _build && cd _build
    - meson setup --buildtype=release
    # Must compile before 'meson dist' to generate source code and documentation.
    - meson compile
    - meson dist
  artifacts:
    name: "${CI_JOB_NAME}-${CI_COMMIT_REF_NAME}"
    when: always
    paths:
      - "_build/meson-dist/*.tar.xz"
